POST https://peternedergaard.xyz/CA2backend/api/login

{username: "user", password: "test123"}


###
GET http://localhost:8080/devops_starter_war_exploded/api/info/user
x-access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjQ5MTUyNzM4LCJpYXQiOjE2NDkxNTA5MzgsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.I1KrON2rUPj4ZpwDPETNz9khKVUiTn4QIvmejVErVyA


###
GET http://localhost:8080/sem3ExamBackend_war_exploded/api/info/allshows

###
GET http://localhost:8080/sem3ExamBackend_war_exploded/api/info/allguests

###
GET http://localhost:8080/sem3ExamBackend_war_exploded/api/info/allfestivals


###
GET http://localhost:8080/sem3ExamBackend_war_exploded/api/info/showsbyguest/3

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/addguesttoshow

{
guestEmail: "Email2",
showName: "Show3"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/createfestival

{
name: "NewestFestival",
city: "NewestCity",
startDate: "NewestStartDate",
duration: "100"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/createshow

{
name: "NewShow",
duration: "30",
location: "NewLocation",
startDate: "NewDate",
startTime: "NewTime"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/createguest

{
name: "NewName",
phone: "NewPhone",
email: "NewEmail",
status: "NewStatus"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/updatefestival

{
name: "NewestFestival",
updatedName: "OldestFestival",
updatedCity: "OldestCity",
updatedStartDate: "OldestStartDate",
updatedDuration: "10"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/updateguest

{
email: "Email1",
updatedName: "UpdatedName",
updatedPhone: "UpdatedPhone",
updatedEmail: "UpdatedEmail",
updatedStatus: "UpdatedStatus"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/updateshow

{
name: "NewShow",
updatedName: "OldShow",
updatedDuration: "30",
updatedLocation: "OldLocation",
updatedStartDate: "OldDate",
updatedStartTime: "OldTime"
}

###
POST http://localhost:8080/sem3ExamBackend_war_exploded/api/info/deleteshow

{
showId: "5"
}